
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.primerapractica.src.tools;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HEADER2 = 7;
  public static final int HEADER1 = 6;
  public static final int PUNTO = 4;
  public static final int TEXTO = 2;
  public static final int ENTERO = 3;
  public static final int LISTA = 5;
  public static final int NEGRITAITALICA = 14;
  public static final int EOF = 0;
  public static final int ITALICA = 13;
  public static final int error = 1;
  public static final int NEGRITA = 12;
  public static final int HEADER6 = 11;
  public static final int HEADER5 = 10;
  public static final int HEADER4 = 9;
  public static final int PARRAFO = 15;
  public static final int HEADER3 = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TEXTO",
  "ENTERO",
  "PUNTO",
  "LISTA",
  "HEADER1",
  "HEADER2",
  "HEADER3",
  "HEADER4",
  "HEADER5",
  "HEADER6",
  "NEGRITA",
  "ITALICA",
  "NEGRITAITALICA",
  "PARRAFO"
  };
}

